trigger:
    - none
  
schedules:
- cron: "0 4 * * *"
  displayName: Daily Midnight Build
  branches:
    include:
    - master
  always: true

pr:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: IMAGERESORUCEGROUP
    value: aib-sig-rg
  - name: IMAGETEMPLATEFILENAME
    value: image-template-win-10.json
  - name: IMAGERESOURCENAME
    value: 01-image-template-win-10-desktop

stages:
# Create Image Stage
- stage: Deploy_Session_Hosts
  displayName: Deploy Session Hosts
  jobs:
    - job: Deploy_Session_Hosts_Job
      displayName: Deploy Session Hosts Job
      steps:
      - checkout: self
        displayName: Clone Git Repo

      - task: Bash@3
        displayName: List Git Repo Content
        inputs:
          targetType: 'inline'
          script: 'ls -al'
      - task: AzureCLI@2
        displayName: Delete Resoruce Group
        inputs:
          azureSubscription: 'AzDevOPS'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az group delete --verbose --name aib-wvd-vmpool-rg
             --yes