trigger:
  - master

pr:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: imageResourceGroup
  value: aib-sig-rg

steps:
- task: AzureCLI@2
  displayName: List Foler Content
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      ls -al

# - task: AzureCLI@2
#   displayName: Create and Set Configuration Variables
#   inputs:
#     azureSubscription: 'AzDevOPS'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       echo "##vso[task.setvariable variable=imageResourceGroup]aib-sig-rg"
#       echo $imageResourceGroup
#     failOnStandardError: true

- task: AzureCLI@2
  displayName: Test Variables
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
        echo '1 - '${{ variables.imageResourceGroup }} # one
        echo '2 - '$(imageResourceGroup) # two
        echo '3 - '$imageResourceGroup # three
    failOnStandardError: true

# - task: AzureCLI@2
#   displayName: Create the Image Template
#   inputs:
#     azureSubscription: 'AzDevOPS'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       imageResourceGroup=aib-sig-rg
#       az resource create --verbose \
#           --resource-group $imageResourceGroup \
#           --properties @helloImageTemplateWin.json \
#           --is-full-object \
#           --resource-type Microsoft.VirtualMachineImages/imageTemplates \
#           -n helloImageTemplateWin10Desktop01

# - task: AzureCLI@2
#   displayName: Create the Image Template
#   inputs:
#     azureSubscription: 'AzDevOPS'
#     scriptType: 'bash'
#     scriptLocation: 'scriptPath'
#     scriptPath: 'create-image.sh'