trigger:
  - master

pr:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: IMAGERESORUCEGROUP
    value: aib_sig_rg

steps:
- task: AzureCLI@2
  displayName: List Git Repo Content
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      ls -al

# - task: Bash@3
#   inputs:
#     filePath: 'test-variables.sh'
#     noProfile: false
#     noRc: false

# - task: AzureCLI@2
#   displayName: Test Variables inline
#   inputs:
#     azureSubscription: 'AzDevOPS'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       printenv
#       echo '-----------------'
#       echo '1 - ' ${{ variables.imageresourcegroup }} # one
#       echo '2 - ' $(imageresourcegroup) # two
#       echo '3 - ' $imageresourcegroup # three
#       echo '4 - ' $IMAGERESOURCEGROUP #four
#     failOnStandardError: true

- task: AzureCLI@2
  displayName: Test Variables in Script
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'test-variables.sh'
    failOnStandardError: true

# - task: AzureCLI@2
#   displayName: Create Image Template
#   inputs:
#     azureSubscription: 'AzDevOPS'
#     scriptType: 'bash'
#     scriptLocation: 'scriptPath'
#     scriptPath: '01-create-image-template.sh'
#     failOnStandardError: true
