trigger:
  - none

pr:
  - none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: Set Environment Variables
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      imageResourceGroup=aib-sig-rg
      echo $imageResourceGroup