trigger:
  - master

pr:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  image_resource_group: aib_sig_rg

steps:
- task: AzureCLI@2
  displayName: List Git Repo Content
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      ls -al

- task: AzureCLI@2
  displayName: Test Variables
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
        echo $(image_resource_group)
    failOnStandardError: true

# - task: AzureCLI@2
#   displayName: Create Image Template
#   inputs:
#     azureSubscription: 'AzDevOPS'
#     scriptType: 'bash'
#     scriptLocation: 'scriptPath'
#     scriptPath: '01-create-image-template.sh'
#     failOnStandardError: true


# - task: AzureCLI@2
#   displayName: Create the Image Template
#   inputs:
#     azureSubscription: 'AzDevOPS'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       imageResourceGroup=aib-sig-rg
#       az resource create --verbose \
#           --resource-group $imageResourceGroup \
#           --properties @helloImageTemplateWin.json \
#           --is-full-object \
#           --resource-type Microsoft.VirtualMachineImages/imageTemplates \
#           -n helloImageTemplateWin10Desktop01

