trigger:
  - none

schedules:
- cron: "0 0 * * *"
  displayName: Daily Midnight Build
  branches:
    include:
    - master
  always: true

pr:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: IMAGERESORUCEGROUP
    value: aib-sig-rg

steps:
- checkout: self
  displayName: Clone Git Repo

- task: AzureCLI@2
  displayName: List Git Repo Content
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      ls -al

- task: AzureCLI@2
  displayName: Create Image Template
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '01-create-image-template.sh'

- task: AzureCLI@2
  displayName: Build Image
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '02-build-image.sh'

- task: AzureCLI@2
  displayName: Delete Image Template
  inputs:
    azureSubscription: 'AzDevOPS'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '03-delete-image-template.sh'