trigger:
    - none
  
schedules:
- cron: "0 4 * * *"
  displayName: Daily Midnight Build
  branches:
    include:
    - master
  always: true

pr:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: IMAGERESORUCEGROUP
    value: aib-sig-rg
  - name: IMAGETEMPLATEFILENAME
    value: image-template-win-10.json
  - name: IMAGERESOURCENAME
    value: 01-image-template-win-10-desktop

stages:
# Create Image Stage
- stage: Deploy_Session_Hosts
  displayName: Deploy Session Hosts
  jobs:
    - job: Deploy_Session_Hosts_Job
      displayName: Deploy Session Hosts Job
      steps:
      - checkout: self
        displayName: Clone Git Repo

      - task: Bash@3
        displayName: List Git Repo Content
        inputs:
          targetType: 'inline'
          script: 'ls -al'

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Deploy Main ARM Template
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'AzDevOPS'
          subscriptionId: '1965c25a-b7fd-48b5-a393-c9e785c1c4d9'
          action: 'DeleteRG'
          resourceGroupName: 'aib-wvd-vmpool-rg'

      # - task: AzureResourceManagerTemplateDeployment@3
      #   displayName: Deploy Main ARM Template
      #   inputs:
      #     deploymentScope: 'Resource Group'
      #     azureResourceManagerConnection: 'AzDevOPS'
      #     subscriptionId: '1965c25a-b7fd-48b5-a393-c9e785c1c4d9'
      #     action: 'Create Or Update Resource Group'
      #     resourceGroupName: 'aib-wvd-hostpool-rg'
      #     location: 'Canada Central'
      #     templateLocation: 'Linked artifact'
      #     csmFile: 'arm-templates/maintemplate.json'
      #     deploymentMode: 'Incremental'