# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

stages:
# Create Prep Deployment 
- stage: Prep_Deployment
  displayName: Prep Deployment
  jobs:
    - job: Download_Repo
      displayName: Download the Repo
      steps:
      - checkout: self
        displayName: Clone Git Repo

      - task: PowerShell@2
        displayName: List Git Repo Content
        inputs:
          targetType: 'inline'
          script: 'ls'

- stage: Cleanup_Session_Hosts_WVD
  displayName: Clean up the session hosts registration

- stage: Cleanup_Sessions_Hosts_RGP
  displayName: Remove the Session Hosts Resource Group

- stage: Create_Session_Hosts
  displayName: Create and Register Session Hosts


  