# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

variables:
  - name: HOSTPOOLRESOURCEGROUPNAME
    value: tbd
  - name: SESSIONHOSTRESOURCEGROUPNAME
    value: aib-wvd-vmpool-rg
  - name: LOCATION
    value: canadacentral

stages:
# Create Prep Deployment 
- stage: Prep_Deployment
  displayName: Prep Deployment
  jobs:
    - job: Download_Repo
      displayName: Download the Repo
      steps:
      - checkout: self
        displayName: Clone Git Repo

      - task: PowerShell@2
        displayName: List Git Repo Content
        inputs:
          targetType: 'inline'
          script: 'ls'

      - task: AzureFileCopy@4
        inputs:
          azureSubscription: 'AzDevOPS'
          SourcePath: '$(Build.Repository.LocalPath)'
          Destination: 'AzureBlob'
          storage: 'azminlandevops'
          ContainerName: 'templates'
          sasTokenTimeOutInMinutes: '240'
      

- stage: Cleanup_Session_Hosts_WVD
  displayName: Clean up the session hosts registration
  jobs: 
  - job: Remove_Session_Hosts_Registration
    displayName: Drain connections, remove users. Remove session hosts from the pool.
    steps:
      - task: AzurePowerShell@5
        inputs:
          azureSubscription: 'AzDevOPS'
          ScriptType: 'FilePath'
          azurePowerShellVersion: 'LatestVersion'


- stage: Cleanup_Sessions_Hosts_RGP
  displayName: Remove the Session Hosts Resource Group
  jobs:
  - job: Remove_Session_Hosts_WVD
    displayName: Remove Session Hosts VMs -> Removing Resource Group
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'AzDevOPS'
        ScriptType: 'InlineScript'
        Inline: 
        azurePowerShellVersion: 'LatestVersion'

- stage: Create_Session_Hosts
  displayName: Create and Register Session Hosts


  