# Pipleine for deploying multiple pods supporting a single persona

trigger:
  - persona-stage

pr:
  - none

pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

parameters:

  - name: targetContainer
    displayName: Target Host Container
    type: string
    values:
      - BLUE
      - GREEN
    default: BLUE

  - name: image
    displayName: Image
    type: string
    default: PR01-WIN10-1909-0620

variables:
  - group: nataliak
  - name: azureConnectionName
    value: AzDevOps2

extends:
  template: pipeline/wvd-pipeline.yml
  parameters:
    personaId: PR12
    personaName: Developers
    primaryRegion: canadacentral
    primaryRegionCode: CACN
    image: ${{ parameters.image }}
    primaryKeyVault: PR12-CACN-KVL
    primaryNetAppInstance: WVD-CACN-NETAPP-PR12
    primaryNetAppCapacity: PR12-CACN-CPOOL
    primaryNetAppVolume: PR12-CACN-VOL
    targetContainer: ${{ parameters.targetContainer }}
    pods:
      - podId: POD01
        numberOfVMs: 3
      - podId: POD02
        numberOfVMs: 2

