# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: targetRegion
    displayName: Target Azure Region for deployment
    type: string
    default: canadacentral
    values:
      - canadacentral
      - canadaeast

  - name: targetContainer
    displayName: Target Host Container
    type: string
    values:
      - blue
      - green

  - name: podId
    displayName: Pod ID (format:POD##, ex POD01)
    type: string
    default: POD01

stages:
  - template: pipeline/prep-stage.yml
    parameters:
      azureSubscription: ""
      storageAccountName: ""
  - template: deploy-pod-stage.yml

  - template: deploy-host-group-stage.yml

  - template: swap-users-stage.yml

  - template: destroy-host-group-stage.yml
