parameters:
  - name: resourceGroupName
  - name: location
  - name: templateFile

jobs:
  - job: ${{ parameters.templateFile }}
    variables:
      - template: vars.yml
    steps:
      - task: AzurePowerShell@4
        inputs:
          azureSubscription: ${{ variables.azureConnectionName }}
          scriptType: inlineScript
          azurePowerShellVersion: "LatestVersion"
          inline: |
            $startTime = Get-Date
            $expiryTime = $startTime.AddMinutes(30)
            Set-AzCurrentStorageAccount -ResourceGroupName "$(storageAccountResourceGroupName)" -Name "$(StorageAccountName)"
            $token = New-AzStorageContainerSASToken -Name "templates" -ExpiryTime $expiryTime -Permission "r"
            Write-Host "##vso[task.setvariable variable=token]$token"

      - task: AzureResourceGroupDeployment@2
        inputs:
          azureSubscription: ${{ variables.azureConnectionName }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          location: ${{ parameters.location }}
          templateLocation: URL of the file
          csmFileLink: "https://$(storageAccountName).blob.core.windows.net/templates/${{parameters.templateFile}}$(token)"
          overrideParameters: "-artifactsLocationSasToken $(token)"
