parameters:
  - name: podResourceGroup
  - name: targetRegion
  - name: keyVaultName

stages:
  # Create new pod resource group and resources
  - stage: Deploy_Pod
    displayName: Deploy Pod
    variables:
      - template: vars.yml
    jobs:
      - template: deploy-template.yml
        parameters:
          resourceGroupName: ${{ parameters.podResourceGroup }}
          location: ${{ parameters.targetRegion }}
          templateFile: patterns/new-pod.json
          templateParameters: |
            -keyVaultName ${{ parameters.keyVaultName }} `
            -addressPrefix $(subnetAddressPrefix-blue) `
            -addressPrefix-green $(subnetAddressPrefix-green)
