parameters:
  - name: podId
    default: ''
  - name: personaId
  - name: environment
    default: WVD
  - name: podResourceGroup
  - name: targetRegion
  - name: keyVaultName

stages:
  # Create new pod resource group and resources
  - stage: DeployPod_${{ parameters.podId }}
    dependsOn: Prep_Deployment
    displayName: Deploy Pod ${{ parameters.podId }}
    jobs:
      - template: deploy-template.yml
        parameters:
          resourceGroupName: ${{ parameters.podResourceGroup }}
          location: ${{ parameters.targetRegion }}
          templateFile: arm-templates/new-pod.json
          parameterArray:
            - keyVaultName ${{ parameters.keyVaultName }}
            - environment ${{ parameters.environment }}
            - persona ${{ parameters.personaId }} 
            - pod ${{ parameters.podId }} 
            - workspaceId $(workspaceId) 
            - userGroupName $(userGroupName) 
            - userGroupObjectId $(userGroupObjectId) 
            - testUserGroupName $(testUserGroupName) 
            - testUserGroupObjectId $(testUserGroupObjectId) 
            - VNETName $(VnetName) 
            - VNETRG $(VnetResourceGroup)
            - AzDevOpsSPN $(SPNApplicationId)

