parameters:
  - name: podId
  - name: location
  - name: targetContainer

stages:
  - stage: Deploy_Host_VMs
    displayName: Deploy Host Pool VMs
    variables:
      keyVaultName: $[dependencies.Deploy_Pod.Deploy_ARM_Template.outputs['Output.keyVaultName']]
      keyVaultRGName: $[dependencies.Deploy_Pod.Deploy_ARM_Template.outputs['Output.keyVaultRGName']]
      blue-subnetID: $[dependencies.Deploy_Pod.Deploy_ARM_Template.outputs['Output.blue-subnetID']]
      green-subnetID: $[dependencies.Deploy_Pod.Deploy_ARM_Template.outputs['Output.green-subnetID']]
    jobs:
      - job: PrintOutputs
        steps:
          - pwsh: |
              Write-Host '$(keyVaultName)'
              Write-Host '$(keyVaultRGName)'
              Write-Host '$(blue-subnetID)'
              Write-Host '$(green-subnetID)'
      - template: deploy-template.yml
        parameters:
          resourceGroupName: ${{ format('$(resourceGroupPrefix)-{0}-{1}', parameters.podId, parameters.targetContainer) }}
          location: ${{ parameters.location }}
          templateFile: arm-templates/empty-template.json
          templateParameters: ""
