parameters:
  - name: podId
  - name: location

stages:
  # Create new pod resource group and resources
  - stage: Deploy_Pod
    displayName: Deploy Pod
    jobs:
      - template: deploy-template.yml
        parameters:
          resourceGroupName: ${{ format('{0}-{1}', variables.resourceGroupPrefix, parameters.podId) }}
          location: ${{ parameters.location }}
          jobName: empty-template
          templateFile: arm-templates/empty-template.json
