parameters:
  - name: podId
  - name: targetRegion
  - name: regionCodes
    type: object
  - name: persona
  - name: targetContainer

stages:
  - stage: Deploy_Host_VMs
    displayName: Deploy Host Pool VMs
    variables:
      ${{ if eq( parameters.targetContainer, 'blue') }}:
        hostPoolName: $[stageDependencies.Deploy_Pod.Deploy_ARM_Template.outputs['Output.blue-hostPoolName']]
        subnetId: blue-subnet-id
        netappShare: netapp-blue

      ${{ if eq( parameters.targetContainer, 'green') }}:
        hostPoolName: $[stageDependencies.Deploy_Pod.Deploy_ARM_Template.outputs['Output.green-hostPoolName']]
        subnetId: green-subnet-id
        netappShare: netapp-green
    jobs:
      - template: deploy-template.yml
        parameters:
          resourceGroupName: $(containerResourceGroup)
          location: ${{ parameters.targetRegion }}
          templateFile: arm-templates/main-template-kv2a.json
          templateParameters: "-VaultName $(keyVaultName) -VaultResourceGroupName $(podResourceGroup) -VaultSubscriptionId $(subscriptionId) -subnetId $(subnetId) -netappshare $(netappShare) -desId $(diskEncryptKeyResourceId) -host-pool-resource-group $(podResourceGroup) -HostPoolName $(hostPoolName)"
