parameters:
  - name: podId
    default: ''
  - name: keyVaultName
  - name: podResourceGroup
  - name: containerResourceGroup
  - name: targetRegion
  - name: targetContainer

stages:
  - stage: Deploy_Host_VMs_${{ parameters.podId }}
    displayName: Deploy Host Pool VMs
    variables:
      ${{ if eq( parameters.targetContainer, 'blue') }}:
        hostPoolName: $[stageDependencies.Deploy_Pod.Deploy_ARM_Template.outputs['Output.blue-hostPoolName']]
        subnetId: blue-subnet-id
        netappShare: netapp-blue

      ${{ if eq( parameters.targetContainer, 'green') }}:
        hostPoolName: $[stageDependencies.Deploy_Pod.Deploy_ARM_Template.outputs['Output.green-hostPoolName']]
        subnetId: green-subnet-id
        netappShare: netapp-green
    jobs:
      - template: deploy-template.yml
        parameters:
          resourceGroupName: ${{ parameters.containerResourceGroup }}
          location: ${{ parameters.targetRegion }}
          templateFile: arm-templates/main-template-kv2a.json
          templateParameters: "-VaultName ${{ parameters.keyVaultName }} -VaultResourceGroupName ${{ parameters.podResourceGroup }} -VaultSubscriptionId $(subscriptionId) -subnetId $(subnetId) -netappshare $(netappShare) -desId $(diskEncryptKeyResourceId) -host-pool-resource-group ${{ parameters.podResourceGroup }} -HostPoolName $(hostPoolName)"
