parameters:
  - name: podId
    default: ''
  - name: personaId
  - name: environment
    default: WVD
  - name: podResourceGroup
  - name: targetRegion
  - name: keyVaultName

stages:
  # Create new pod resource group and resources
  - stage: DeployPod_${{ parameters.podId }}
    dependsOn: Prep_Deployment
    displayName: Deploy Pod ${{ parameters.podId }}
    variables:
      - template: vars.yml
    jobs:
      - template: deploy-template.yml
        parameters:
          resourceGroupName: ${{ parameters.podResourceGroup }}
          location: ${{ parameters.targetRegion }}
          templateFile: patterns/new-pod.json
          templateParameters: -keyVaultName ${{ parameters.keyVaultName }} -environment ${{ parameters.environment }} -persona ${{ parameters.personaId }} -pod ${{ parameters.podId }} -workspaceId $(workspaceId) -_artifactsLocation "https://$(storageAccountName).blob.core.windows.net/" -userGroupName $(userGroupName) -userGroupObjectId $(userGroupObjectId) -testUserGroupName $(testUserGroupName) -testUserGroupObjectId $(testUserGroupObjectId) -VNETName $(VnetName) -VNETRG $(VnetResourceGroup)

