parameters:
  - name: podId
    default: ''
  - name: personaId
  - name: numberOfVMs
    type: number
  - name: keyVaultName
  - name: podResourceGroup
  - name: containerResourceGroup
  - name: targetRegion
  - name: targetContainer

stages:
  - stage: Deploy_Host_VMs_${{ parameters.podId }}
    dependsOn: DeployPod_${{ parameters.podId }}
    displayName: Deploy VMs ${{ parameters.podId}}
    variables:
      ${{ if eq( parameters.targetContainer, 'blue') }}:
        hostPoolName: $[stageDependencies.DeployPod_${{ parameters.podId }}.Deploy_ARM_Template.outputs['Output.blue-hostPoolName']]
        subnetId: blue-subnet-id
        netappShare: netapp-blue

      ${{ if eq( parameters.targetContainer, 'green') }}:
        hostPoolName: $[stageDependencies.DeployPod_${{ parameters.podId }}.Deploy_ARM_Template.outputs['Output.green-hostPoolName']]
        subnetId: green-subnet-id
        netappShare: netapp-green
    jobs:
      - template: deploy-template.yml
        parameters:
          preDeploySteps:
            - task: AzurePowerShell@4
              displayName: Get latest image version
              inputs:
                pwsh: true
                azureSubscription: $(azureConnectionName)
                scriptType: inlineScript
                azurePowerShellVersion: LatestVersion
                inline: |
                  $ImageDef = "${{ parameters.personaId }}"

                  $LatestVersion = Get-AzGalleryImageVersion -ResourceGroupName $(sigRG) -GalleryName $(sigName) -GalleryImageDefinitionName $ImageDef |
                    Select -Property Name,@{l="PublishedDate";e={$_.PublishingProfile.PublishedDate}} |
                    Sort-Object PublishedDate -Descending |
                    Select -First 1
                  
                  if(!$LatestVersion) { 
                    throw "Latest image version not found for SigRG: $(sigRG), Name: $(sigName), Def: $ImageDef"
                  }

                  Write-Host "Latest Version: $LatestVersion"
                  Write-Host "##vso[task.setvariable variable=sigVersion]$LatestVersion"

          resourceGroupName: ${{ parameters.containerResourceGroup }}
          location: ${{ parameters.targetRegion }}
          templateFile: arm-templates/main-template-kv2a.json
          parameterArray:
            - _artifactsLocation "https://$(storageAccountName).blob.core.windows.net/"
            - VaultName ${{ parameters.keyVaultName }}
            - VaultResourceGroupName ${{ parameters.podResourceGroup }}
            - VaultSubscriptionId $(subscriptionId)
            - useSharedImage $(useSharedImage)
            - subnetId $(subnetId)
            - netappshare $(netappShare)
            - desId $(diskEncryptKeyResourceId)
            - host-pool-resource-group ${{ parameters.podResourceGroup }}
            - HostPoolName $(hostPoolName)
            - workspaceId $(workspaceId)
            - joinDomain $(joinDomain)
            - instance-count ${{ parameters.numberOfVMs }}
            - shared-image-gallery-rg $(sigRG)
            - shared-image-gallery-name $(sigName)
            - shared-image-gallery-definition ${{ parameters.personaId }}
            - shared-image-gallery-version $(sigVersion)
