parameters:
  - name: podId
  - name: targetRegion
  - name: regionCodes
  - name: persona

stages:
  # Create new pod resource group and resources
  - stage: Deploy_Pod
    displayName: Deploy Pod
    variables:
      - template: vars.yml
    jobs:
      - template: deploy-template.yml
        parameters:
          resourceGroupName: $(podResourceGroup)
          location: ${{ parameters.targetRegion }}
          templateFile: patterns/new-pod.json
          templateParameters: |
            -keyVaultName $(keyVaultName) `
            -addressPrefix $(subnetAddressPrefix-blue) `
            -addressPrefix-green $(subnetAddressPrefix-green)
