parameters:
  - name: resourceGroupName
  - name: location
  - name: templateFile
  - name: parameterArray
    type: object
  - name: jobName
    default: Deploy_ARM_Template

jobs:
  - job: ${{ parameters.jobName }}
    displayName: Deploy ${{ parameters.templateFile }}
    variables:
      - template: vars.yml
    steps:
      - template: deploy-template-steps.yml
        parameters:
          resourceGroupName: ${{ parameters.resourceGroupName }}
          location: ${{ parameters.location }}
          templateFile: ${{ parameters.templateFile }}
          parameterArray: ${{ parameters.parameterArray }}
