parameters:
  - name: personaId
    displayName: Persona ID
    type: string

  - name: personaName
    displayName: Persona Name
    type: string

  - name: image
    displayName: Persona Image
    type: string

  - name: podId
    displayName: Pod ID
    type: string

  - name: numberOfVMs
    displayName: Number of VMs
    type: number

  - name: podDiscription
    type: string

  - name: podResourceGroup
    type: string

  - name: targetRegion
    type: string

  - name: targetContainer
    type: string

stages:

  - template: deploy-pod-stage.yml
    parameters:
      podId: ${{ parameters.podId }}
      personaId: ${{ parameters.personaId }}
      podResourceGroup: ${{ parameters.podResourceGroup }}
      targetRegion: ${{ parameters.targetRegion }}
      keyVaultName: ${{ format('WVD-KVL-{0}-{1}', parameters.personaId, parameters.podId) }}

  - template: deploy-host-pool-vms-stage.yml
    parameters:
      podId: ${{ parameters.podId }}
      numberOfVMs: ${{ parameters.numberOfVMs }}
      keyVaultName: ${{ format('WVD-KVL-{0}-{1}', parameters.personaId, parameters.podId) }}
      podResourceGroup: ${{ parameters.podResourceGroup }}
      containerResourceGroup: ${{ format('{0}-{1}', parameters.podResourceGroup, parameters.targetContainer) }}
      targetRegion: ${{ parameters.targetRegion }}
      targetContainer: ${{ parameters.targetContainer }}

  - template: swap-users-stage.yml
    parameters:
      podId: ${{ parameters.podId }}
      personaId: ${{ parameters.personaId }}
      keyVaultName: ${{ format('WVD-KVL-{0}-{1}', parameters.personaId, parameters.podId) }}
      podResourceGroup: ${{ parameters.podResourceGroup }}