parameters:
  - name: storageAccountName
    type: string
  - name: azureConnectionName
    type: string

stages:
  # Create Prep Deployment
  - stage: Prep_Deployment
    displayName: Prep Deployment
    jobs:
      - job: Download_Repo
        displayName: Download the Repo
        steps:
          - checkout: self
            displayName: Clone Git Repo

          - task: PowerShell@2
            displayName: List Git Repo Content
            inputs:
              targetType: "inline"
              script: "ls"

          - task: AzureFileCopy@4
            inputs:
              azureSubscription: ${{ parameters.azureConnectionName }}
              SourcePath: '$(Build.Repository.LocalPath)\*'
              Destination: "AzureBlob"
              storage: ${{ parameters.storageAccountName }}
              ContainerName: "templates"
              sasTokenTimeOutInMinutes: "240"
