parameters:
  - name: podId
    default: ''
  - name: keyVaultName
  - name: podResourceGroup

stages:
  - stage: Swap_Users_${{ parameters.podId }}
    displayName: Swap Users
    dependsOn:
      - Deploy_Pod
      - Deploy_Host_VMs
    variables:
      - template: vars.yml
      - name: keyVaultName
        value: ${{ parameters.keyVaultName }}
      - name: podResourceGroup
        value: ${{ parameters.podResourceGroup }}
    jobs:
      - job: Swap_App_Group_Users
        displayName: Swap App Group Users
        steps:
          - task: AzurePowerShell@4
            displayName: Swap Users Script
            inputs:
              pwsh: true
              azureSubscription: ${{ variables.azureConnectionName }}
              scriptType: filePath
              azurePowerShellVersion: "LatestVersion"
              scriptPath: $(Build.Repository.LocalPath)\misc\Switch-Users-App-Group.ps1
              scriptArguments: -VaultName $(keyVaultName) -VaultResourceGroupName $(podResourceGroup) -SubscriptionId $(subscriptionId) -ActiveHostResourceGroupName $(podResourceGroup)
