
parameters:
  - name: personaId
    displayName: Persona ID
    type: string

  - name: personaName
    displayName: Persona Name
    type: string

  - name: primaryRegion
    displayName: Primary Region
    type: string
    values:
      - canadacentral
      - canadaeast
    default: canadacentral

  - name: primaryRegionCode
    displayName: Primary Region Code
    type: string
    values:
      - CACN
      - CAET
    default: CACN

  - name: image
    displayName: Persona Image
    type: string

  - name: primaryKeyVault
    displayName: Key Vault Resource Id  - Primary Region
    type: string

  - name: primaryNetAppInstance
    displayName: NetApp Instance - Primary Region
    type: string

  - name: primaryNetAppCapacity
    displayName: NetApp Capacity Pool - Primary Region
    type: string

  - name: primaryNetAppVolume
    displayName: NetApp Capacity Pool - Primary Region
    type: string

  - name: pods
    displayName: Pods
    type: object
    default:
      - podId: POD01
        numberOfVMs: 2
      - podId: POD02
        numberOfVMs: 2
  
  - name: targetContainer
    displayName: Target Container
    type: string
    default: blue
    values:
      - BLUE
      - GREEN

  - name: environment
    displayName: Environment
    type: string
    default: WVD
    values:
      - SBX
      - DEV
      - PRD
      - WVD

stages:
  - template: prep-stage.yml
  - template: persona-stage.yml
    parameters:
      personaId: ${{ parameters.personaId }}
      pods: ${{ parameters.pods}}
      NetAppResourceGroup: $(NetAppResourceGroup)
      targetRegion: ${{ parameters.primaryRegion }}
  - ${{ each pod in parameters.pods }}:
    - template: pod-template.yml
      parameters:
        personaId: ${{ parameters.personaId }}
        personaName: ${{ parameters.personaName }}
        image: ${{ parameters.image }}
        podId: ${{ pod.podId }}
        numberOfVMs: ${{ pod.numberOfVMs }}
        podDiscription: ${{ format('{0} {1}', parameters.personaName, pod.podId)}}
        podResourceGroup: ${{ format('{0}-RGP-{1}-{2}', parameters.environment, parameters.personaId, pod.podId)}}
        targetRegion: ${{ parameters.primaryRegion }}
        targetContainer: ${{ parameters.targetContainer }}
